apiVersion: v1
kind: Namespace
metadata:
  name: longhorn
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 60m
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  chart:
    spec:
      chart: longhorn
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 12h
      reconcileStrategy: ChartVersion
  interval: 1h
  timeout: 5m
  maxHistory: 5
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    presistence:
      defaultClass: false
      defaultDataLocality: best-effort
      defaultClassReplicaCount: 1
    defaultSettings:
      defaultReplicaCount: 1
      systemManagedComponentsNodeSelector: "k3s.shangkuei.xyz/longhorn:true"
    longhornManager:
      log:
        format: json
