apiVersion: v1
kind: Namespace
metadata:
  name: media
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-runner
  namespace: media
  labels:
    control-plane: controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: media-tf-runner-rolebinding
  namespace: media
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tf-runner-role
subjects:
  - kind: ServiceAccount
    name: tf-runner
    namespace: media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tf-runner-reconciler
  namespace: media
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: gotk:media:reconciler
  - kind: ServiceAccount
    name: tf-runner
    namespace: media
