apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nfs-provisioner
  namespace: nfs-provisioner
spec:
  interval: 60m
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: nfs-provisioner
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "v4.x"
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
      interval: 12h
      reconcileStrategy: ChartVersion
  interval: 1h
  timeout: 5m
  maxHistory: 5
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    replicaCount: 1
    fullnameOverride: nfs-provisioner
    storageClass:
      name: synology-nfs
      provisionerName: k3s.shangkuei.xyz/synology-nfs
      onDelete: retain
      accessModes: ReadWriteMany
      volumeBindingMode: Immediate
    nfs:
      server: 192.168.1.20
      path: /volume1/cloud
      mountOptions:
        - async
        - resvport
        - rw
      volumeName: synology-nfs
      reclaimPolicy: Retain
    labels:
      k3s.shangkuei.xyz/storage-class: synology-nfs
