apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-csi
  namespace: vault
spec:
  dependsOn:
    - name: vault-ha
      namespace: vault
  chart:
    spec:
      chart: vault
      version: v0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      interval: 12h
      reconcileStrategy: ChartVersion
  interval: 1h
  timeout: 10m
  maxHistory: 5
  install:
    crds: Skip
  upgrade:
    cleanupOnFail: true
    crds: Skip
  uninstall:
    keepHistory: false
  values:
    nameOverride: vault-ha
    fullnameOverride: vault-ha
    global:
      enabled: false
      # tlsDisable: false
    csi:
      enabled: true
      daemonSet:
        updateStrategy:
          minAvailable: "1"
