---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 12h
  ref:
    branch: main
  url: https://github.com/shangkuei/fluxcd.git
---
apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-git-repository-reconciler
  namespace: monitoring
spec:
  # clean up the job after the kustomization reconcile timeout
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: tf-runner
      containers:
        - name: flux-cli
          image: fluxcd/flux-cli:v0.41.1
          imagePullPolicy: IfNotPresent
          args:
            - reconcile
            - source
            - git
            - -n
            - monitoring
            - prometheus
      volumes:
        - name: dummy
          configMap:
            name: prometheus-git-repository-reconciler
      restartPolicy: OnFailure
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: prometheus
  namespace: monitoring
spec:
  dependsOn:
    - name: vault-ha
      namespace: vault
  sourceRef:
    kind: GitRepository
    name: prometheus
  path: monitoring/prometheus/provision/terraform
  interval: 1h
  retryInterval: 5m
  destroyResourcesOnDeletion: true
  refreshBeforeApply: true
  storeReadablePlan: human
  approvePlan: auto
  writeOutputsToSecret:
    name: prometheus-vault-token
