---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
          - "@prettier/plugin-xml"
          - prettier-plugin-go-template
          - prettier-plugin-toml
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: remove-crlf
      - id: remove-tabs
        args: [--whitespaces-count, "2"]
  - repo: https://github.com/sirosen/texthooks
    rev: 0.5.0
    hooks:
      - id: fix-smartquotes
      - id: fix-spaces
      - id: fix-ligatures
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint
        args:
          - --config-file
          - .yamllint.yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: requirements-txt-fixer
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.5
    hooks:
      - id: ripsecrets
