---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: coredns-scaler
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: utils/cluster-proportional-autoscaler/
  interval: 1h
  timeout: 5m
  force: true
  prune: true
  targetNamespace: kube-system
  postBuild:
    substitute:
      linear_autocaler_name: coredns-scaler
      linear_autocaler_namespace: kube-system
      linear_autocaler_fullname_override: coredns-scaler
      linear_autocaler_target: deployment/coredns
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: coredns-scaler
      namespace: kube-system
