apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: media-base
  namespace: flux-system
spec:
  dependsOn:
    # The media flow should wait until the flux system is ready.
    - name: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: media/base
  interval: 1h
  timeout: 10m
  force: true
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: media-plex-meta-manager-terraform-credential
  namespace: flux-system
spec:
  dependsOn:
    # The credential terraform stack stack should wait until the tf-controller is ready.
    - name: flux-system
    # The credential terraform stack should wait until the vault-ha is ready.
    - name: vault-ha-helm-release
    # The credential terraform stack should wait until the vault-ha terraform stack is ready.
    - name: vault-ha-terraform-provision
    # The credential terraform stack should wait until the media-base is ready.
    - name: media-base
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: flux-system
  path: media/plex-meta-manager/credential
  interval: 1h
  timeout: 10m
  force: true
  prune: true
  healthChecks:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      name: plex-meta-manager-credential
      namespace: media
    - apiVersion: infra.contrib.fluxcd.io/v1alpha1
      kind: Terraform
      name: plex-meta-manager-credential
      namespace: media
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: media-plex-meta-manager
  namespace: flux-system
spec:
  dependsOn:
    # The plex meta manager should wait until the nfs-provisioner is ready.
    - name: nfs-provisioner
    # The plex meta manager  stack should wait until the vault-ha is ready.
    - name: vault-ha-helm-release
    # The plex meta manager  should wait until the media-base is ready.
    - name: media-base
    # The plex meta manager should wait until the credentials terraform stack is ready.
    - name: media-terraform-credentials
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: media/plex-meta-manager
  interval: 1h
  timeout: 10m
  force: true
  prune: true
  wait: true
