apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-base
  namespace: flux-system
spec:
  dependsOn:
    # The monitoring flow should wait until the flux system is ready.
    - name: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: monitoring/base
  interval: 1h
  timeout: 5m
  force: true
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    # The prometheus stack should wait until the nfs-provisioner is ready.
    - name: nfs-provisioner
    # The prometheus stack should wait until the monitoring-base is ready.
    - name: monitoring-base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: monitoring/prometheus
  interval: 1h
  timeout: 5m
  force: true
  prune: true
  wait: true
