---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-base
  namespace: flux-system
spec:
  dependsOn:
    # The monitoring flow should wait until the flux system is ready.
    - name: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: monitoring/base
  interval: 1h
  timeout: 10m
  force: true
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    # The prometheus stack should wait until the nfs-provisioner is ready.
    - name: nfs-provisioner
    # The prometheus stack should wait until the monitoring-base is ready.
    - name: monitoring-base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: monitoring/prometheus
  interval: 1h
  timeout: 10m
  force: true
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: prometheus-operator-operator
      namespace: monitoring
    - apiVersion: apps/v1
      kind: StatefulSet
      name: prometheus-prometheus
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: prometheus-kube-state-metrics
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: alertmanager-operator
      namespace: monitoring
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-grafana-terraform-provision
  namespace: flux-system
spec:
  dependsOn:
    # The grafana provision stack should wait until the tf-controller is ready.
    - name: flux-system
    # The grafana provision stack should wait until the vault-ha provision stack is ready.
    - name: vault-ha-terraform-provision
    # The grafana provision stack should wait until the monitoring-base is ready.
    - name: monitoring-base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: monitoring/grafana/provision
  interval: 1h
  timeout: 10m
  force: true
  prune: true
  healthChecks:
    - apiVersion: infra.contrib.fluxcd.io/v1alpha1
      kind: Terraform
      name: grafana
      namespace: monitoring
