---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: nfs-provisioner/
  interval: 1h
  timeout: 5m
  force: true
  prune: true
  wait: true
