---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: nfs-provisioner/
  interval: 1h
  timeout: 10m
  force: true
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta2
      kind: HelmRelease
      name: nfs-provisioner
      namespace: nfs-provisioner
    - apiVersion: apps/v1
      kind: Deployment
      name: nfs-provisioner
      namespace: nfs-provisioner
