---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secrets-store-csi
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: secrets-store-csi/
  interval: 1h
  timeout: 10m
  force: true
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta2
      kind: HelmRelease
      name: secrets-store-csi
      namespace: secrets-store-csi
    - apiVersion: apps/v1
      kind: DaemonSet
      name: secrets-store-csi
      namespace: secrets-store-csi
