---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: secret-store-csi
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: secret-store-csi/
  interval: 1h
  timeout: 10m
  force: true
  prune: true
  wait: true
