---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-base
  namespace: flux-system
spec:
  dependsOn:
    # The vault flow should wait until the flux system is ready.
    - name: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: vault/base
  interval: 1h
  timeout: 10m
  force: true
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-dev-helm-release
  namespace: flux-system
spec:
  dependsOn:
    # The vault-dev should wait until the vault-base is ready for the helm repo.
    - name: vault-base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: vault/dev
  interval: 1h
  timeout: 10m
  force: true
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: vault-dev
      namespace: vault
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-dev-terraform-provision
  namespace: flux-system
spec:
  dependsOn:
    # The vaule-dev provision stack should wait until the tf-controller is ready.
    - name: flux-system
    # The vaule-dev provision stack should wait until the vault-base is ready.
    - name: vault-base
    # The vaule-dev provision stack should wait until the vault-dev is ready.
    - name: vault-dev-helm-release
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: flux-system
  path: vault/dev/provision
  interval: 1h
  timeout: 10m
  force: true
  prune: true
  healthChecks:
    - apiVersion: infra.contrib.fluxcd.io/v1alpha1
      kind: Terraform
      name: vault-dev
      namespace: vault
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-ha-helm-release
  namespace: flux-system
spec:
  dependsOn:
    # The vault-ha should wait until the vault-base is ready for the helm repo.
    - name: vault-base
    # The vaule-ha should wait until the vault-dev is ready.
    - name: vault-dev-helm-release
    # The vaule-ha should wait until the vault-dev Terraform provision stack is ready.
    - name: vault-dev-terraform-provision
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: vault/ha
  interval: 1h
  timeout: 10m
  force: true
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: vault-ha
      namespace: vault
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-ha-terraform-provision
  namespace: flux-system
spec:
  dependsOn:
    # The vaule-ha provision stack should wait until the tf-controller is ready.
    - name: flux-system
    # The vaule-ha provision stack should wait until the vault-base is ready.
    - name: vault-base
    # The vaule-ha provision stack should wait until the vault-dev is ready.
    - name: vault-ha-helm-release
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: flux-system
  path: vault/ha/provision
  interval: 1h
  timeout: 10m
  force: true
  prune: true
  healthChecks:
    - apiVersion: infra.contrib.fluxcd.io/v1alpha1
      kind: Terraform
      name: vault-ha
      namespace: vault
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-csi-helm-release
  namespace: flux-system
spec:
  dependsOn:
    # The vault-csi should wait until the vault-base is ready for the helm repo.
    - name: vault-base
    # The vaule-csi should wait until the vault-ha is ready.
    - name: vault-ha-helm-release
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: vault/ha
  interval: 1h
  timeout: 10m
  force: true
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: vault-ha-csi-provider
      namespace: vault
