---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-base
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: vault/base
  interval: 1h
  timeout: 5m
  force: true
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-dev-helm-release
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
    - name: vault-base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: vault/dev
  interval: 1h
  timeout: 5m
  force: true
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: vault-dev
      namespace: vault
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-dev-terraform-bootstrap
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
    - name: vault-base
    - name: vault-dev-helm-release
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: flux-system
  path: vault/dev/bootstrap
  interval: 1h
  timeout: 5m
  force: true
  prune: true
  healthChecks:
    - apiVersion: infra.contrib.fluxcd.io/v1alpha1
      kind: Terraform
      name: vault-dev
      namespace: vault
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-ha-helm-release
  namespace: flux-system
spec:
  dependsOn:
    - name: vault-base
    - name: vault-dev-helm-release
    - name: vault-dev-terraform-bootstrap
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: vault/ha
  interval: 1h
  timeout: 5m
  force: true
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: vault-ha
      namespace: vault
