---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: vault/
  interval: 1h
  timeout: 5m
  force: true
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: vault-dev
      namespace: vault
    - apiVersion: apps/v1
      kind: StatefulSet
      name: vault
      namespace: vault
