---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: vault-ha
  namespace: vault
spec:
  interval: 12h
  ref:
    branch: main
  url: https://github.com/shangkuei/fluxcd.git
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: vault-ha
  namespace: vault
spec:
  sourceRef:
    kind: GitRepository
    name: vault-ha
  path: vault/ha/provision/terraform
  interval: 1h
  retryInterval: 5m
  destroyResourcesOnDeletion: true
  refreshBeforeApply: true
  storeReadablePlan: human
  approvePlan: auto
  varsFrom:
    - kind: Secret
      name: vault-ha-token
