apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: vault-ha
  namespace: vault
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: vault/ha/provision/terraform
  interval: 1h
  destroyResourcesOnDeletion: true
  refreshBeforeApply: true
  storeReadablePlan: human
  approvePlan: auto
  varsFrom:
    - kind: Secret
      name: vault-ha-token
