apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-sync.yaml
  - gotk-components.yaml
patches:
  - path: gotk-healthcheck.yaml
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: helm-controller
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: kustomize-controller
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: notification-controller
  # - patch: |
  #     - op: replace
  #       path: /spec/replicas
  #       value: 2
  #   target:
  #     kind: Deployment
  #     name: source-controller
