apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-sync.yaml
  - gotk-components.yaml
  - tf-components.yaml
patches:
  # Configure health check for flux-system
  - path: gotk-healthcheck.yaml
  # Update flux-system replicas
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: helm-controller
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: kustomize-controller
  - patch: |
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: notification-controller
  # - patch: |
  #     - op: replace
  #       path: /spec/replicas
  #       value: 2
  #   target:
  #     kind: Deployment
  #     name: source-controller
  # Add tf-controller into notifications
  - patch: |
      - op: add
        path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/eventSources/items/properties/kind/enum/-
        value: Terraform
      - op: add
        path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/eventSources/items/properties/kind/enum/-
        value: Terraform
    target:
      kind: CustomResourceDefinition
      name: alerts.notification.toolkit.fluxcd.io
  - patch: |
      - op: add
        path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/resources/items/properties/kind/enum/-
        value: Terraform
      - op: add
        path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/resources/items/properties/kind/enum/-
        value: Terraform
    target:
      kind: CustomResourceDefinition
      name: receivers.notification.toolkit.fluxcd.io
  - patch: |
      - op: add
        path: /rules/-
        value:
          apiGroups: [ 'infra.contrib.fluxcd.io' ]
          resources: [ '*' ]
          verbs: [ '*' ]
    target:
      kind: ClusterRole
      name: crd-controller-flux-system
