---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  provider: vault
  secretObjects:
    - data:
        - key: username
          objectName: username
        - key: password
          objectName: password
      secretName: grafana-admin
      type: Opaque
  parameters:
    roleName: monitoring-grafana
    vaultAddress: "http://vault-ha.vault:8200"
    # vaultTLSServerName: "vault.shangkuei.xyz"
    # vaultCACertPath: '/vault/tls/ca.crt'
    audience: secrets-store-csi
    objects: |
      - objectName: "username"
        secretPath: "secret/monitoring/data/grafana/admin"
        secretKey: "username"
      - objectName: "password"
        secretPath: "secret/monitoring/data/grafana/admin"
        secretKey: "password"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      version: "43.x"
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 1h
  timeout: 10m
  maxHistory: 5
  install:
    crds: Skip
  upgrade:
    cleanupOnFail: true
    crds: Skip
  uninstall:
    keepHistory: false
  values:
    nameOverride: kube-prometheus-stack
    fullnameOverride: grafana
    defaultRules:
      create: false
    global:
      rbac:
        create: true
        createAggregateClusterRoles: true
    alertmanager:
      enabled: false
    prometheus:
      enabled: false
    prometheusOperator:
      enabled: false
    kubeApiServer:
      enabled: false
    kubelet:
      enabled: false
    kubeControllerManager:
      enabled: false
    coreDns:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kubeStateMetrics:
      enabled: false
    nodeExporter:
      enabled: false
    grafana:
      enabled: true
      defaultDashboardsTimezone: Asia/Taipei
      podDisruptionBudget:
        minAvailable: 1
      persistOence:
        enabled: true
        type: pvc
        storageClassName: synology-nfs
        accessModes:
          - ReadWriteOnce
        size: 10Gi
      # nfs storage doesn't support chown
      initChownData:
        enabled: false
      adminPassword: null
      admin:
        existingSecret: grafana-admin
        userKey: username
        passwordKey: password
      extraVolumeMounts:
        - name: grafana-admin
          csi: true
          mountPath: /vault/csi/admin
          data:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: grafana-admin
    cleanPrometheusOperatorObjectNames: true
