---
apiVersion: v1
kind: Namespace
metadata:
  name: secrets-store-csi
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: secrets-store-csi
  namespace: secrets-store-csi
spec:
  interval: 60m
  url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-store-csi
  namespace: secrets-store-csi
spec:
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: "v1.x"
      sourceRef:
        kind: HelmRepository
        name: repo-secrets-store-csi-driver
        namespace: flux-helm
      interval: 12h
      reconcileStrategy: ChartVersion
  interval: 1h
  timeout: 10m
  maxHistory: 5
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    syncSecret:
      enabled: true
    tokenRequests:
      - audience: secrets-store-csi
    enableSecretRotation: true
