apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - chart-nfs-subdir-external-provisioner.yaml
  - chart-democratic-csi.yaml
  - chart-secrets-store-csi-driver.yaml
  - chart-longhorn.yaml
configMapGenerator:
  - name: longhorn-dashboards
    namespace: kube-storage
    files:
      - longhorn-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: longhorn
        app.kubernetes.io/component: monitoring
