---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: vault-dev
  namespace: vault
spec:
  interval: 12h
  ref:
    branch: main
  url: https://github.com/shangkuei/fluxcd.git
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vault-dev-git-repository-reconciler
  namespace: vault
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      serviceAccountName: tf-runner
      containers:
        - name: flux-cli
          image: fluxcd/flux-cli:v0.41.1
          imagePullPolicy: IfNotPresent
          args:
            - reconcile
            - source
            - git
            - -n
            - vault
            - vault-dev
      volumes:
        - name: dummy
          configMap:
            name: vault-dev-git-repository-reconciler
      restartPolicy: OnFailure
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: vault-dev
  namespace: vault
spec:
  sourceRef:
    kind: GitRepository
    name: vault-dev
  path: vault/dev/provision/terraform
  interval: 1h
  retryInterval: 5m
  destroyResourcesOnDeletion: true
  refreshBeforeApply: true
  storeReadablePlan: human
  approvePlan: auto
  varsFrom:
    - kind: Secret
      name: vault-dev-token
  writeOutputsToSecret:
    name: vault-ha-transit-token
