apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault-dev-token.sops.yaml
  - components.yaml
configMapGenerator:
  - name: vault-dev-git-repository-reconciler
    namespace: vault
