apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: vault-dev
  namespace: vault
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: vault/dev/provision/terraform
  interval: 1h
  destroyResourcesOnDeletion: true
  refreshBeforeApply: true
  storeReadablePlan: human
  approvePlan: auto
  varsFrom:
    - kind: Secret
      name: vault-dev-token
  writeOutputsToSecret:
    name: vault-ha-transit-token
