apiVersion: v1
kind: Secret
metadata:
  name: vault-dev-token
  namespace: vault
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:I8mTSZXJ/jMdXuzVFCooKhQ2E/mXtDl4nDbXcQ==,iv:ThVBVTBnAogLuGx8JGkcCp9UdCIPd5J6UGJXJtmG9nQ=,tag:/fcAfcxiYnzTs06BAs/Apg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age123vdkkw4z7e4xxh0xq6dmnwg82kzf86uxkjajs74klg5wkqxvpgq6cwv07
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWGdaWFozbkhLZExsSHZh
        dFpRWjJoTjUvaVJKZGtHN3VHKy9HcDU2TlE4CmxaUVhSZHNpTEF6dXFaK0JGVFdT
        QVYxeWMyTkdVRlkwc082Wi9Yd0dUNXMKLS0tIDNjcDRNMXUwcmlSNTA2Q0VUcGRh
        OW5JbCtZZnhVUSt5TVUzTU1OaEVjaHMKcD/yjKCxYFfMpUGvfzdwNSAgn9LhcEM7
        pkcQjSx82wy3MnxJMmeH/fHF23ym8zkpKVytvPb3nz9CcJydzvivEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-03-10T03:00:06Z"
  mac: ENC[AES256_GCM,data:IC31btck9E0NoUY5z6RLTjlZ26E0lafqUq9hDNHpQTXDaPuIuJXICdd8s3WTWZ3UIh0wM3L9z7ausTOUjYxToHlFQxHGWbStU4Tsgw6/Pl8++fhauGtO1ZBYqrQax9O3AM8hhELpUmPp9UUCDkG/k+F7PBKRaE/H03BP/OwJjpA=,iv:sHGRcVq8uOTvxwRxICqzmZaEZU9pGIyKiZzRiaAf1q0=,tag:Y2XA4X/MYkGeDKYfAID5uA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
