apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  chart:
    spec:
      version: "43.x"
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 1h
  timeout: 10m
  maxHistory: 5
  install:
    crds: Create
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    nameOverride: prometheus-operator
    fullnameOverride: ""
    global:
      rbac:
        create: true
        createAggregateClusterRoles: true
    alertmanager:
      enabled: false
    prometheus:
      enabled: false
    grafana:
      enabled: false
    kubeApiServer:
      enabled: false
    kubelet:
      enabled: false
    kubeControllerManager:
      enabled: false
    coreDns:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kubeStateMetrics:
      enabled: false
    nodeExporter:
      enabled: false
    prometheusOperator:
      enabled: true
    cleanPrometheusOperatorObjectNames: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  dependsOn:
    - name: prometheus-operator
  chart:
    spec:
      version: "43.x"
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 1h
  timeout: 10m
  maxHistory: 5
  install:
    crds: Skip
  upgrade:
    cleanupOnFail: true
    crds: Skip
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: vaules-node
      optional: true
  values:
    nameOverride: prometheus
    fullnameOverride: ""
    global:
      rbac:
        create: true
        createAggregateClusterRoles: true
    alertmanager:
      enabled: false
    prometheusOperator:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: true
      serviceAccount:
        name: prometheus
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      prometheusSpec:
        logfmt: json
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: synology-nfs
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 100Gi
            selector: {}
    kubeApiServer:
      enabled: true
    kubelet:
      enabled: true
    kubeControllerManager:
      enabled: true
    coreDns:
      enabled: true
    kubeEtcd:
      enabled: true
    kubeScheduler:
      enabled: true
    kubeProxy:
      enabled: true
    kubeStateMetrics:
      enabled: true
      nameverride: kube-state-metrics
      fullnameOverride: kube-state-metrics
      serviceAccount:
        name: kube-state-metrics
      selfMonitor:
        enabled: true
    nodeExporter:
      enabled: true
      nameverride: node-exporter
      fullnameOverride: node-exporter
      serviceAccount:
        name: node-exporter
    cleanPrometheusOperatorObjectNames: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  dependsOn:
    - name: prometheus-operator
  chart:
    spec:
      version: "43.x"
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 1h
  timeout: 10m
  maxHistory: 5
  install:
    crds: Skip
  upgrade:
    cleanupOnFail: true
    crds: Skip
  uninstall:
    keepHistory: false
  values:
    nameOverride: alertmanager
    fullnameOverride: ""
    global:
      rbac:
        create: true
        createAggregateClusterRoles: true
    prometheus:
      enabled: false
    grafana:
      enabled: false
    kubeApiServer:
      enabled: false
    kubelet:
      enabled: false
    kubeControllerManager:
      enabled: false
    coreDns:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kubeStateMetrics:
      enabled: false
    nodeExporter:
      enabled: false
    prometheusOperator:
      enabled: false
    alertmanager:
      enabled: true
      serviceAccount:
        name: alertmanager
    cleanPrometheusOperatorObjectNames: true
