apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - components.yaml
configMapGenerator:
  - name: values-node
    namespace: monitoring
    files:
      - values-node.yaml=node.yaml
configurations:
  - kustomizeconfig.yaml
