apiVersion: v1
kind: ServiceAccount
metadata:
  name: plex-meta-manager
  namespace: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex-meta-manager
  name: plex-meta-manager-top
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-nfs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex-meta-manager
  name: plex-meta-manager-movie
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-nfs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex-meta-manager
  name: plex-meta-manager-show
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-nfs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: plex-meta-manager-top-metadata
  namespace: media
spec:
  schedule: "0 0 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            # https://developer.hashicorp.com/vault/docs/platform/k8s/injector/annotations
            vault.hashicorp.com/agent-extra-secret: "pmm-config-template"
            # vault.hashicorp.com/ca-cert: "/vault/custom/ca.cert.pem"
            # vault.hashicorp.com/tls-server-name: "vault.shangkuei.xyz"
            vault.hashicorp.com/service: "http://vault-ha.vault:8200"
            vault.hashicorp.com/auth-path: "auth/kubernetes"
            vault.hashicorp.com/role: "plex-meta-manager"
            vault.hashicorp.com/agent-init-first: "true"
            vault.hashicorp.com/agent-pre-populate: "true"
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-inject-status: "update"
            vault.hashicorp.com/agent-inject-secret-config.yaml: "secret/media/data/plex/config"
            vault.hashicorp.com/agent-inject-template-file-config.yaml: "/vault/custom/config-top-metadata.yaml.tmpl"
        spec:
          serviceAccountName: plex-meta-manager
          securityContext:
            runAsUser: 1024
            runAsGroup: 100
          initContainers:
            - name: init-config
              image: busybox
              command:
                - sh
                - -c
                - >
                  mkdir -p /config/assets &&
                  cp /vault/secrets/config.yaml /config/config-metadata.yaml
              volumeMounts:
                - name: pmm
                  mountPath: /config
          containers:
            - name: plex-meta-manager
              # https://metamanager.wiki/en/latest/home/guides/images.html
              image: meisnate12/plex-meta-manager:latest
              imagePullPolicy: IfNotPresent
              args:
                - --run
                - --read-only-config
                - --config
                - /config/config-metadata.yaml
                - --width
                - "200"
              resources:
                limits:
                  cpu: 100m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 125Mi
              volumeMounts:
                - name: pmm
                  mountPath: /config
                - name: pmm-template
                  mountPath: /config/templates
                - name: nas-video
                  mountPath: /nas-video
              env:
                - name: TZ
                  value: Asia/Taipei
          volumes:
            - name: nas-video
              nfs:
                server: 192.168.1.20
                path: /volume1/video
            - name: pmm
              persistentVolumeClaim:
                claimName: plex-meta-manager-top
            - name: pmm-template
              configMap:
                name: pmm-template
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: plex-meta-manager-top-collection
  namespace: media
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            # https://developer.hashicorp.com/vault/docs/platform/k8s/injector/annotations
            vault.hashicorp.com/agent-extra-secret: "pmm-config-template"
            # vault.hashicorp.com/ca-cert: "/vault/custom/ca.cert.pem"
            # vault.hashicorp.com/tls-server-name: "vault.shangkuei.xyz"
            vault.hashicorp.com/service: "http://vault-ha.vault:8200"
            vault.hashicorp.com/auth-path: "auth/kubernetes"
            vault.hashicorp.com/role: "plex-meta-manager"
            vault.hashicorp.com/agent-init-first: "true"
            vault.hashicorp.com/agent-pre-populate: "true"
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-inject-status: "update"
            vault.hashicorp.com/agent-inject-secret-config.yaml: "secret/media/data/plex/config"
            vault.hashicorp.com/agent-inject-template-file-config.yaml: "/vault/custom/config-top-collection.yaml.tmpl"
        spec:
          serviceAccountName: plex-meta-manager
          securityContext:
            runAsUser: 1024
            runAsGroup: 100
          initContainers:
            - name: init-config
              image: busybox
              command:
                - sh
                - -c
                - >
                  mkdir -p /config/assets &&
                  cp /vault/secrets/config.yaml /config/config.yaml
              volumeMounts:
                - name: pmm
                  mountPath: /config
          containers:
            - name: plex-meta-manager
              # https://metamanager.wiki/en/latest/home/guides/images.html
              image: meisnate12/plex-meta-manager:latest
              imagePullPolicy: IfNotPresent
              args:
                - --run
                - --read-only-config
                - --config
                - /config/config.yaml
                - --width
                - "200"
              resources:
                limits:
                  cpu: 100m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 125Mi
              volumeMounts:
                - name: pmm
                  mountPath: /config
                - name: pmm-template
                  mountPath: /config/templates
                - name: nas-video
                  mountPath: /nas-video
              env:
                - name: TZ
                  value: Asia/Taipei
          volumes:
            - name: nas-video
              nfs:
                server: 192.168.1.20
                path: /volume1/video
            - name: pmm
              persistentVolumeClaim:
                claimName: plex-meta-manager-top
            - name: pmm-template
              configMap:
                name: pmm-template
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: plex-meta-manager-movie
  namespace: media
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            # https://developer.hashicorp.com/vault/docs/platform/k8s/injector/annotations
            vault.hashicorp.com/agent-extra-secret: "pmm-config-template"
            # vault.hashicorp.com/ca-cert: "/vault/custom/ca.cert.pem"
            # vault.hashicorp.com/tls-server-name: "vault.shangkuei.xyz"
            vault.hashicorp.com/service: "http://vault-ha.vault:8200"
            vault.hashicorp.com/auth-path: "auth/kubernetes"
            vault.hashicorp.com/role: "plex-meta-manager"
            vault.hashicorp.com/agent-init-first: "true"
            vault.hashicorp.com/agent-pre-populate: "true"
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-inject-status: "update"
            vault.hashicorp.com/agent-inject-secret-config.yaml: "secret/media/data/plex/config"
            vault.hashicorp.com/agent-inject-template-file-config.yaml: "/vault/custom/config-movie.yaml.tmpl"
        spec:
          serviceAccountName: plex-meta-manager
          securityContext:
            runAsUser: 1024
            runAsGroup: 100
          initContainers:
            - name: init-config
              image: busybox
              command:
                - sh
                - -c
                - >
                  mkdir -p /config/assets &&
                  cp /vault/secrets/config.yaml /config/config.yaml
              volumeMounts:
                - name: pmm
                  mountPath: /config
          containers:
            - name: plex-meta-manager
              # https://metamanager.wiki/en/latest/home/guides/images.html
              image: meisnate12/plex-meta-manager:latest
              imagePullPolicy: IfNotPresent
              args:
                - --run
                - --read-only-config
                - --config
                - /config/config.yaml
                - --width
                - "200"
              resources:
                limits:
                  cpu: 100m
                  memory: 1Gi
                requests:
                  cpu: 100m
                  memory: 125Mi
              volumeMounts:
                - name: pmm
                  mountPath: /config
                - name: pmm-template
                  mountPath: /config/templates
                - name: nas-radarr
                  mountPath: /nas-radarr
              env:
                - name: TZ
                  value: Asia/Taipei
          volumes:
            - name: nas-radarr
              nfs:
                server: 192.168.1.20
                path: /volume1/radarr
            - name: pmm
              persistentVolumeClaim:
                claimName: plex-meta-manager-movie
            - name: pmm-template
              configMap:
                name: pmm-template
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: plex-meta-manager-show
  namespace: media
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            # https://developer.hashicorp.com/vault/docs/platform/k8s/injector/annotations
            vault.hashicorp.com/agent-extra-secret: "pmm-config-template"
            # vault.hashicorp.com/ca-cert: "/vault/custom/ca.cert.pem"
            # vault.hashicorp.com/tls-server-name: "vault.shangkuei.xyz"
            vault.hashicorp.com/service: "http://vault-ha.vault:8200"
            vault.hashicorp.com/auth-path: "auth/kubernetes"
            vault.hashicorp.com/role: "plex-meta-manager"
            vault.hashicorp.com/agent-init-first: "true"
            vault.hashicorp.com/agent-pre-populate: "true"
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-inject-status: "update"
            vault.hashicorp.com/agent-inject-secret-config.yaml: "secret/media/data/plex/config"
            vault.hashicorp.com/agent-inject-template-file-config.yaml: "/vault/custom/config-show.yaml.tmpl"
        spec:
          serviceAccountName: plex-meta-manager
          securityContext:
            runAsUser: 1024
            runAsGroup: 100
          initContainers:
            - name: init-config
              image: busybox
              command:
                - sh
                - -c
                - >
                  mkdir -p /config/assets &&
                  cp /vault/secrets/config.yaml /config/config.yaml
              volumeMounts:
                - name: pmm
                  mountPath: /config
          containers:
            - name: plex-meta-manager
              # https://metamanager.wiki/en/latest/home/guides/images.html
              image: meisnate12/plex-meta-manager:latest
              imagePullPolicy: IfNotPresent
              args:
                - --run
                - --read-only-config
                - --config
                - /config/config.yaml
                - --width
                - "200"
              resources:
                limits:
                  cpu: 100m
                  memory: 1Gi
                requests:
                  cpu: 100m
                  memory: 125Mi
              volumeMounts:
                - name: pmm
                  mountPath: /config
                - name: pmm-template
                  mountPath: /config/templates
                - name: nas-sonarr
                  mountPath: /nas-sonarr
              env:
                - name: TZ
                  value: Asia/Taipei
          volumes:
            - name: nas-sonarr
              nfs:
                server: 192.168.1.20
                path: /volume1/sonarr
            - name: pmm
              persistentVolumeClaim:
                claimName: plex-meta-manager-show
            - name: pmm-template
              configMap:
                name: pmm-template
          restartPolicy: OnFailure
