apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: pmm-config-template
    namespace: media
    files:
      - config-movie.yaml.tmpl
      - config-show.yaml.tmpl
      - config-top-metadata.yaml.tmpl
      - config-top-collection.yaml.tmpl
    options:
      disableNameSuffixHash: true
configMapGenerator:
  - name: pmm-template
    namespace: media
    files:
      - template/actor.yaml
      - template/genre.yaml
      - template/radarr.yaml
      - template/resolution.yaml
      - template/sonarr.yaml
      - template/studio.yaml
      - template/tmdb.yaml
      - template/writer.yaml
resources:
  - components.yaml
