apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: plex-meta-manager-credential
  namespace: media
spec:
  dependsOn:
    - name: vault-ha
      namespace: vault
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: media/plex-meta-manager/credential/terraform
  interval: 1h
  retryInterval: 5m
  destroyResourcesOnDeletion: true
  refreshBeforeApply: true
  storeReadablePlan: human
  approvePlan: auto
  varsFrom:
    - kind: Secret
      name: plex-meta-manager-credential
