---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: plex-meta-manager-credential
  namespace: media
spec:
  interval: 12h
  ref:
    branch: main
  url: https://github.com/shangkuei/fluxcd.git
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: plex-meta-manager-credential
  namespace: media
spec:
  dependsOn:
    - name: vault-ha
      namespace: vault
  sourceRef:
    kind: GitRepository
    name: plex-meta-manager-credential
  path: media/plex-meta-manager/credential/terraform
  interval: 1h
  retryInterval: 5m
  destroyResourcesOnDeletion: true
  refreshBeforeApply: true
  storeReadablePlan: human
  approvePlan: auto
  varsFrom:
    - kind: Secret
      name: plex-meta-manager-credential
