apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - components.yaml
  - plex-meta-manager-credential.sops.yaml
configMapGenerator:
  - name: plex-meta-manager-credential-git-repository-reconciler
    namespace: media
