apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-ha
  namespace: vault
spec:
  dependsOn:
    - name: nfs-provisioner
      namespace: nfs-provisioner
    - name: vault-dev
      namespace: vault
  chart:
    spec:
      chart: vault
      version: v0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      interval: 12h
      reconcileStrategy: ChartVersion
  interval: 1h
  timeout: 10m
  maxHistory: 5
  install:
    crds: Create
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    # global:
    #   tlsDisable: false
    injector:
      logLevel: info
      logFormat: json
      replica: 3
      metrics:
        enabled: true
      revokeOnShutdown: true
      podDisruptionBudget:
        maxUnavailable: 1
    server:
      updateStrategyType: RollingUpdate
      logLevel: info
      logFormat: json
      service:
        clusterIP: None
      dataStorage:
        size: 1Gi
        storageClass: synology-nfs
      auditStorage:
        enabled: true
        size: 500Mi
        storageClass: synology-nfs
      extraInitContainers:
        - name: busybox
          image: busybox
          command:
            - sh
            - -c
          args:
            - |
              cat <<EOF > /vault/userconfig/vault-seal-config.hcl
              seal "transit" {
                address         = "http://vault-dev:8200"
                token           = "$(cat /vault/secret/transit-token)"
                disable_renewal = "false"
                key_name        = "vault-ha"
                mount_path      = "transit/"
                tls_skip_verify = "true"
              }
          volumeMounts:
            - name: userconfig
              mountPath: /vault/userconfig
            - name: transit-token
              mountPath: /vault/secret
              readOnly: true
      volumes:
        - name: userconfig
          emptyDir: {}
        - name: transit-token
          secret:
            defaultMode: 400
            secretName: vault-ha-transit-token
      volumeMounts:
        - name: userconfig
          mountPath: /vault/userconfig
          readOnly: true
      extraArgs: -config=/vault/userconfig/vault-seal-config.hcl
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          config: |
            ui = true

            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }

            storage "raft" {
              path = "/vault/data"
              retry_join {
                leader_api_addr = "http://vault-ha-0.vault-ha-internal:8200"
              }
              retry_join {
                leader_api_addr = "http://vault-ha-1.vault-ha-internal:8200"
              }
              retry_join {
                leader_api_addr = "http://vault-ha-2.vault-ha-internal:8200"
              }
            }

            telemetry {
              prometheus_retention_time = "24h"
              disable_hostname = true
            }

            service_registration "kubernetes" {}
    ui:
      enabled: true
      publishNotReadyAddresses: false
      activeVaultPodOnly: true
    csi:
      enabled: false
